# next: impute solar and wind forecasting data
Note: From 05/01/2018, there are two forecasts for the same target in different period. 
Currently: choose the latest forecast

# impute forecast date

In [1]:
import pandas as pd, math, numpy as np
import sys 
sys.path.append('C:\\Users\\Nuo.Chen\\PycharmProjects\\Imbalance_price_forecast')
from utils.import_packages import *
from data_gathering import *
from features.features import *

impute strategy:
1. the forecast is per hour, then evenly shared the power output for the four quarters. 
2. if the hourly-forecast is missing, find next or previous year's data in the same period same day
3. otherwise, missing values are filled with average power output in the same period of the whole data. 

Note: there are about 89% of missingd data in the forecasting data

In [2]:
# get solar and wind value divide by four
solar_wind_col = ['solar_value', 'solar_maxvalue', 'solar_minvalue', 'wind_value', 'wind_maxvalue', 'wind_minvalue']
solar_wind_df = pd.read_excel(weather_folder + '/complete_solar_wind.xlsx')
solar_wind_df[ solar_wind_col ]/=4

solar_wind_df.to_excel(weather_folder + '/averaged_solar_wind.xlsx', index = False)

In [55]:
impute_solar_wind_df = pd.read_excel(weather_folder + '/averaged_solar_wind.xlsx')
impute_solar_wind_df.head()

,DateTime,Date,PTE,solar_value,solar_maxvalue,solar_minvalue,wind_value,wind_maxvalue,wind_minvalue
0,2015-09-23 00:00:00,2015-09-23,1,0.0,0.0,0.0,27.1075,32.425,22.65
1,2015-09-23 00:15:00,2015-09-23,2,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-09-23 00:30:00,2015-09-23,3,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-09-23 00:45:00,2015-09-23,4,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-09-23 01:00:00,2015-09-23,5,0.0,0.0,0.0,29.8025,38.225,25.35

In [8]:
import time
start = time.time()

# impute 
for index, row in impute_solar_wind_df.iterrows():
       
    current_PTE = impute_solar_wind_df.loc[index]['PTE']
    
    if row.isnull().any():
        # contain missing values
        if current_PTE % 4 == 1 | impute_solar_wind_df.loc[index-1].isnull().any():
            # missing forecast data
            continue
        
        # impute the same value to four PTE within an hour
        impute_solar_wind_df.loc[index,solar_wind_col] = impute_solar_wind_df.loc[index-1, solar_wind_col]

end = time.time()

print(end - start)

KeyboardInterrupt:

In [ ]:
# takes: 16:37

In [56]:
# test if quicker than last version
impute_solar_wind_df = pd.read_excel(weather_folder + '/averaged_solar_wind.xlsx')
# impute_solar_wind_df.head()

import time
start = time.time()

# impute 
for index, row in impute_solar_wind_df.iterrows():
    
#     if index > 10:
#         break
       
    current_PTE = impute_solar_wind_df.loc[index]['PTE']
    
    if current_PTE % 4 ==1 : # hourly
        continue
    
    last_row = impute_solar_wind_df.loc[index-1][solar_wind_col]
    
    if last_row.isnull().any():
        continue
    
    impute_solar_wind_df.loc[index, solar_wind_col] = last_row[solar_wind_col]
    

duration = (time.time() - start)

print('takes:{} s'.format(duration))

impute_solar_wind_df.tail()

KeyboardInterrupt:

In [58]:
impute_solar_wind_df = pd.read_excel(weather_folder + '/averaged_solar_wind.xlsx')

cur_index = 0
import time
start = time.time()

while cur_index < len(impute_solar_wind_df):
#     if cur_index > 20:
#         break
    
    PTE = impute_solar_wind_df.loc[cur_index]['PTE']
#     print(PTE)

    cur_row = impute_solar_wind_df.loc[cur_index][solar_wind_col]
    
    if PTE % 4 == 1 & cur_row.isnull().any():
        cur_index +=96
        continue
    
    if PTE % 4 ==1:
#         print('impute the following three lines')
        impute_solar_wind_df.loc[cur_index+1, solar_wind_col] = cur_row
        impute_solar_wind_df.loc[cur_index+2, solar_wind_col] = cur_row
        impute_solar_wind_df.loc[cur_index+3, solar_wind_col] = cur_row
        cur_index += 4
        continue
    

    raise ValueError('Invalid missing values')
    
end = time.time()

print('takes:{} min'.format((end - start)/60))
impute_solar_wind_df.tail()

takes:2.4893999059995013 min

,DateTime,Date,PTE,solar_value,solar_maxvalue,solar_minvalue,wind_value,wind_maxvalue,wind_minvalue
96091,2018-06-19 22:45:00,2018-06-19,92,0.277594,0.45,0.15,88.043981,369.5,1.600
96092,2018-06-19 23:00:00,2018-06-19,93,0.000000,0.00,0.00,105.082639,407.3,3.025
96093,2018-06-19 23:15:00,2018-06-19,94,0.000000,0.00,0.00,105.082639,407.3,3.025
96094,2018-06-19 23:30:00,2018-06-19,95,0.000000,0.00,0.00,105.082639,407.3,3.025
96095,2018-06-19 23:45:00,2018-06-19,96,0.000000,0.00,0.00,105.082639,407.3,3.025

In [35]:
impute_solar_wind_df.tail()
impute_solar_wind_df.to_excel(weather_folder + '/imputed_solar_wind.xlsx')

In [98]:
# impute using two passes
for index, row in solar_wind_df.iterrows():
    if index > 0:
        break
    print(solar_wind_df.loc[index])
    if not row.isnull().any():
        solar_wind_df.ix[index][['solar_value', 'solar_maxvalue', 'solar_minvalue', 'wind_value', 'wind_maxvalue', 'wind_minvalue']]/=4
        print(solar_wind_df.loc[index])

solar_wind_df.head(15)

DateTime          2015-09-23 00:00:00
Date              2015-09-23 00:00:00
PTE                                 1
solar_value                         0
solar_maxvalue                      0
solar_minvalue                      0
wind_value                     108.43
wind_maxvalue                   129.7
wind_minvalue                    90.6
Name: 0, dtype: object
DateTime          2015-09-23 00:00:00
Date              2015-09-23 00:00:00
PTE                                 1
solar_value                         0
solar_maxvalue                      0
solar_minvalue                      0
wind_value                     108.43
wind_maxvalue                   129.7
wind_minvalue                    90.6
Name: 0, dtype: object

,DateTime,Date,PTE,solar_value,solar_maxvalue,solar_minvalue,wind_value,wind_maxvalue,wind_minvalue
0,2015-09-23 00:00:00,2015-09-23,1,0.0,0.0,0.0,108.43,129.7,90.6
1,2015-09-23 00:15:00,2015-09-23,2,NaN,NaN,NaN,NaN,NaN,NaN
2,2015-09-23 00:30:00,2015-09-23,3,NaN,NaN,NaN,NaN,NaN,NaN
3,2015-09-23 00:45:00,2015-09-23,4,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-09-23 01:00:00,2015-09-23,5,0.0,0.0,0.0,119.21,152.9,101.4
5,2015-09-23 01:15:00,2015-09-23,6,NaN,NaN,NaN,NaN,NaN,NaN
6,2015-09-23 01:30:00,2015-09-23,7,NaN,NaN,NaN,NaN,NaN,NaN
7,2015-09-23 01:45:00,2015-09-23,8,NaN,NaN,NaN,NaN,NaN,NaN
8,2015-09-23 02:00:00,2015-09-23,9,0.0,0.0,0.0,130.05,178.9,114.1
9,2015-09-23 02:15:00,2015-09-23,10,NaN,NaN,NaN,NaN,NaN,NaN
10,2015-09-23 02:30:00,2015-09-23,11,NaN,NaN,NaN,NaN,NaN,NaN
11,2015-09-23 02:45:00,2015-09-23,12,NaN,NaN,NaN,NaN,NaN,NaN
12,2015-09-23 03:00:00,2015-09-23,13,0.0,0.0,0.0,138.02,200.1,118.6
13,2015-09-23 03:15:00,2015-09-23,14,NaN,NaN,NaN,NaN,NaN,NaN
14,2015-09-23 03:30:00,2015-09-23,15,NaN,NaN,NaN,NaN,NaN,NaN

In [83]:
# impute using two pass
for index, row in solar_wind_df.iterrows():
    
    
    
    
    
    
    next_year_today = row['DateTime'].replace(year = row['DateTime'].year +1 )
    print(row['DateTime'], next_year_today)

2015-09-23 00:00:00 2016-09-23 00:00:00
2015-09-23 00:15:00 2016-09-23 00:15:00
2015-09-23 00:30:00 2016-09-23 00:30:00
2015-09-23 00:45:00 2016-09-23 00:45:00
2015-09-23 01:00:00 2016-09-23 01:00:00
2015-09-23 01:15:00 2016-09-23 01:15:00
2015-09-23 01:30:00 2016-09-23 01:30:00
2015-09-23 01:45:00 2016-09-23 01:45:00
2015-09-23 02:00:00 2016-09-23 02:00:00
2015-09-23 02:15:00 2016-09-23 02:15:00
2015-09-23 02:30:00 2016-09-23 02:30:00
2015-09-23 02:45:00 2016-09-23 02:45:00
2015-09-23 03:00:00 2016-09-23 03:00:00
2015-09-23 03:15:00 2016-09-23 03:15:00
2015-09-23 03:30:00 2016-09-23 03:30:00
2015-09-23 03:45:00 2016-09-23 03:45:00

In [ ]:
while current_row_index <= solar_wind_df.index[-1]:
    
    if row.isnull().any():
        # impute
        if solar_wind_df.loc[ 4 - current_row_index%4 ].isnull().any():
            # impute last year today
            while(true):
                next_year_today = row['DateTime'].replace(year = row['DateTime'].year +1 )
                if solar_wind_df[ solar_wind_df['DateTime'] == next_year_today].isnull().any():
                    next_year_today =

In [70]:
# evenly share the hourly-fourecast
for index, row in solar_wind_df.iterrows():
    if index > 15:
        break
    
    current_PTE = row['PTE']
    
    if row.isnull().any():
        # has missing value
        if index 
        row[['solar_value']]
        print(index)
    if current_PTE % 4 == 1:
        # supposed to have forecast
        s,s_max,s_min,w,w_max,w_min = row[['solar_value','solar_maxvalue','solar_minvalue','wind_value','wind_maxvalue','wind_minvalue']].values
        print(s,s_max, s_min, w, w_max, w_min)

0.0 0.0 0.0 108.43 129.7 90.6
1
2
3
0.0 0.0 0.0 119.21 152.9 101.4
5
6
7
0.0 0.0 0.0 130.05 178.9 114.1
9
10
11
0.0 0.0 0.0 138.02 200.1 118.6
13
14
15

In [7]:
# convert date
date = dsolar_df['Date']
date = strptime(string, "%d %b %Y  %H:%M:%S.%f")

,TIMESTAMP_UTC,VENDOR_ID,PERIOD,value,maxvalue,minvalue,CREATED_TIMESTAMP_UTC,COUNTRY_ID
0,2015-09-23 00:00:00,MKON,H,0.0,0.0,0.0,2015-09-22,NL
1,2015-09-23 01:00:00,MKON,H,0.0,0.0,0.0,2015-09-22,NL
2,2015-09-23 02:00:00,MKON,H,0.0,0.0,0.0,2015-09-22,NL
3,2015-09-23 03:00:00,MKON,H,0.0,0.0,0.0,2015-09-22,NL
4,2015-09-23 04:00:00,MKON,H,0.0,0.0,0.0,2015-09-22,NL

## extract date, PTE...

In [ ]:
# no need to process system_imbalance_data table n

In [3]:
system_imbalance_df.columns

Index(['week', 'Date', 'PTE', 'period_from', 'period_until',
       'upward_incident_reserve', 'downward_incident_reserve',
       'upward_dispatch_EURMwh', 'downward_dispatch_kWhPTE',
       'incentive_component_EURMwh', 'take_from_system_kWhPTE',
       'feed_into_system_EURMwh', 'Regulation state', 'purchase_kWhPTE',
       'sell_kWhPTE', 'absolute_kWhPTE', 'imbalance_kWhPTE',
       'downward_reserve_kWh_PTE', 'downward_power_kWh_PTE',
       'upward_power_kWh_PTE', 'upward_reserve_kWh_PTE',
       'upward_incident_reserve_kWh_PTE', 'downward_incident_reserve_kWh_PTE',
       'volume_kWhPTE', 'totals_kWhPTE'],
      dtype='object')

In [4]:
system_df = system_imbalance_df[['week', 'Date', 'PTE', 'take_from_system_kWhPTE',\
                                'feed_into_system_EURMwh','Regulation state', 'purchase_kWhPTE',\
                                'sell_kWhPTE', 'absolute_kWhPTE', 'imbalance_kWhPTE']]

In [15]:
df = system_df

# train test split

In [6]:
train_size = 0.7
unique_days = np.unique( df['Date'].values )
split_date = unique_days[ math.floor(len(unique_days)*train_size)]
split_date

'09/06/2012'

In [7]:
split_index = df.index[df['Date'] == split_date].tolist()[0]

# make target

In [16]:
df.columns

Index(['week', 'Date', 'PTE', 'take_from_system_kWhPTE',
       'feed_into_system_EURMwh', 'Regulation state', 'purchase_kWhPTE',
       'sell_kWhPTE', 'absolute_kWhPTE', 'imbalance_kWhPTE'],
      dtype='object')

In [17]:
target = df['imbalance_kWhPTE']
X = df[['week', 'Date', 'PTE']]